on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
        description: "azure aks credenials"

      AZURE_RESOURCE_GROUP:
        required: true
        description: "azure aks resource group"

      AKS_CLUSTER_NAME:
        required: true
        description: "azure aks cluster name"

    inputs:
      app_branch:
        required: true
        type: string

      # For disfferent microservice project path in monorepo
      deployed_app:
        required: true
        type: string

      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: uat

jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{inputs.currentEnvironment}} artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.currentEnvironment}}_${{github.sha}}
          path: artifacts

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Set latest Image version to AKS
        run: |
          sed -i 's|image:.*|image: '"$IMAGE_TAG"'|' deployment.yaml

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml

      - name: Wait for Deployment to Complete
        run: |
          kubectl rollout status deployment/${{ inputs.deployed_app }} --timeout=300s
