on:
  workflow_call:
    secrets:
      DOCKER_SERVER:
        required: true
        description: "azure acr server"

      AZURE_CREDENTIALS:
        required: true
        description: "azure aks credenials"

      AZURE_RESOURCE_GROUP:
        required: true
        description: "azure aks resource group"

      AKS_CLUSTER_NAME:
        required: true
        description: "azure aks cluster name"

      AKS_NAMESPACE:
        required: true
        description: "azure aks application namespace"

    inputs:
      app_branch:
        required: true
        type: string

      # For disfferent microservice project path in monorepo
      deployed_app:
        required: true
        type: string

      image_tag:
        required: true
        type: string

      artifact_name:
        required: true
        type: string
      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: uat

jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{inputs.currentEnvironment}} artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: ${{secrets.DOCKER_SERVER}}/${{inputs.image_tag}}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          name: ${{ secrets.AKS_CLUSTER_NAME }}
          namespace: ${{ secrets.AKS_NAMESPACE }}
