on:
  workflow_call:
    secrets:
      DOCKER_SERVER:
        required: true
        description: "azure acr server"

      AZURE_RESOURCE_GROUP:
        required: true
        description: "azure aks resource group"

      AKS_CLUSTER_NAME:
        required: true
        description: "azure aks cluster name"

      AKS_NAMESPACE:
        required: true
        description: "azure aks application namespace"

      AZURE_CLIENT_ID:
        required: true
        description: "azure aks client id"

      AZURE_TENANT_ID:
        required: true
        description: "azure aks tenant id"

      AZURE_SUBSCRIPTION_ID:
        required: true
        description: "azure aks subscription id"

      AZURE_CREDS:
        required: true
        description: "azure aks subscription id"

    inputs:
      image_tag:
        required: true
        type: string

      artifact_name:
        required: true
        type: string

      # the path of the aks manifest file
      aks_manifests_path:
        required: false
        type: string
        default: "k8s"

      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: uat

permissions:
  id-token: write
  contents: read
jobs:
  Deplpy-To-AKS:
    runs-on: ubuntu-latest
    environment: ${{ inputs.currentEnvironment }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifacts

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: ${{ inputs.currentEnvironment }}
          # creds: ${{ secrets.AZURE_CREDS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ inputs.aks_manifests_path }}
          images: ${{secrets.DOCKER_SERVER}}/${{inputs.image_tag}}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          name: ${{ secrets.AKS_CLUSTER_NAME }}
          namespace: ${{ secrets.AKS_NAMESPACE }}
