on:
  workflow_call:
    secrets:
      DOCKER_SERVER:
        required: true
        description: "azure acr server"

      DOCKER_USERNAME:
        required: true
        description: "azure acr username"

      DOCKER_PASSWORD:
        required: true
        description: "azure acr password"

    inputs:
      app_branch:
        required: true
        type: string

      # For disfferent microservice project path in monorepo
      deployed_app:
        required: true
        type: string

      # the docker file path
      dockerFile_path:
        required: false
        type: string
        default: Dockerfile

      # Build artifact options--------------------------------

      build_path:
        required: false
        type: string
        default: build

      # the environment that u want to deploy (uat,prod)
      currentEnvironment:
        required: true
        type: string
        default: uat

jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Download ${{inputs.currentEnvironment}} artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.currentEnvironment}}_${{github.sha}}
          path: artifacts

        # Add support for more platforms with QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker target Registry
        uses: docker/login-action@v3
        with:
          registry: ${{secrets.DOCKER_SERVER}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd ./artifacts
          UTC_TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          IMAGE_TAG=${{secrets.DOCKER_SERVER}}/${{inputs.deployed_app}}:${{inputs.currentEnvironment}}_${{github.sha}}_${UTC_TIMESTAMP}
          docker build -f ./${{inputs.dockerFile_path}} --build-arg BUILD_COMMAND=build:${{inputs.currentEnvironment}} -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_TAG }}
